# This is a basic workflow to help you get started with Actions

name: Build & Release

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Install NodeJS and NPM
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install
        
      # Build the bundle
      - name: Build bundle
        run: |
          npm run build --if-present --skipLibCheck
          zip -r nodecg-graphic-previewer.zip package.json node_modules package-lock.json dashboard extension README.md LICENSE
          tar -cvf nodecg-graphic-previewer.tar package.json node_modules package-lock.json dashboard extension README.md LICENSE

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.1.0"
          prerelease: false
          title: "Development Build"
          files: |
            *.zip
            *.tar
